export const TeamsCallsDescription = [
  'omówiono zagadnienia związane z optymalizacją kodu przez zespół BE',
  'przedstawiono nowe funkcjonalności do zaimplementowania przez zespół FE',
  'wyjaśniono problemy związane z testowaniem jednostkowym przez testerów',
  'przeanalizowano wyniki testów automatycznych',
  'zidentyfikowano błędy w aplikacji i zaproponowano poprawki',
  'przedyskutowano wymagania biznesowe i ich wpływ na implementację',
  'skupiono się na poprawie wydajności aplikacji front-endowej',
  'przeprowadzono burzę mózgów dotyczącą nowych funkcji w aplikacji',
  'omówiono sposoby poprawy komunikacji między zespołem FE a zespołem BE',
  'zaktualizowano status bieżących zadań i przypisano nowe',
  'zaprezentowano postęp prac nad projektem',
  'wyjaśniono specyfikacje techniczne niezbędne do realizacji zadania przez zespół BE',
  'przedstawiono feedback od użytkowników końcowych',
  'skoncentrowano się na analizie wymagań funkcjonalnych',
  'uzgodniono priorytety na nadchodzący tydzień',
  'omówiono wyniki ostatniego audytu wewnętrznego',
  'podsumowano najważniejsze wnioski z ostatnich spotkań',
  'przedstawiono strategie zarządzania zmianami w projekcie',
  'omówiono metody poprawy wydajności zespołu',
  'wypracowano plan działania na najbliższe dni',
  'przeanalizowano feedback od interesariuszy projektu',
  'uzgodniono terminy realizacji poszczególnych zadań',
  'omówiono rozwiązania alternatywne dla obecnych problemów',
  'skupiono się na integracji nowych narzędzi w procesie',
  'przedyskutowano kwestie związane z budżetem i zasobami projektu'
];

export const FEDevDescription = [
  'zaimplementowano nowe komponenty do wyświetlania listy produktów',
  'dokonano refaktoryzacji kodu odpowiedzialnego za obsługę formularzy rejestracyjnych',
  'zoptymalizowano wydajność ładowania strony głównej',
  'przeprowadzono aktualizację biblioteki komponentów do najnowszej wersji',
  'naprawiono błędy związane z walidacją pól formularza',
  'przeprowadzono testy jednostkowe dla serwisów komunikujących się z API',
  'skonfigurowano narzędzia do ciągłej integracji i wdrożenia aplikacji',
  'przeanalizowano i wdrożono najlepsze praktyki dotyczące zarządzania stanem aplikacji',
  'omówiono wymagania i zdefiniowano zakres pracy dla modułu zarządzania użytkownikami',
  'przeprowadzono audyt wydajności aplikacji pod kątem szybkości ładowania zasobów',
  'zntegrowano zewnętrzną bibliotekę do obsługi map z aplikacją',
  'przeprowadzono code review kodu odpowiedzialnego za routing w aplikacji',
  'wdrożono aktualizację widoków aby dopasować je do makiet',
  'zaktualizowano dokumentację techniczną modułu autoryzacji użytkowników',
  'przeprowadzono migrację stylów z CSS do SCSS w celu lepszej organizacji kodu',
  'zaimplementowano mechanizm lazy loading dla modułów aplikacji',
  'zoptymalizowano działanie animacji interfejsu użytkownika',
  'naprawiono problemy z kompatybilnością aplikacji na starszych przeglądarkach',
  'skonfigurowano środowisko deweloperskie z wykorzystaniem Docker',
  'dodano obsługę trybu ciemnego w ustawieniach użytkownika',
  'przeprowadzono testy end-to-end dla kluczowych ścieżek użytkownika',
  'wdrożono mechanizmy cache\'owania danych pobieranych z API',
  'skonfigurowano wielojęzyczność w aplikacji za pomocą biblioteki ngx-translate',
  'dodano możliwość sortowania i filtrowania listy produktów',
  'zaimplementowano dynamiczne ładowanie komponentów na podstawie uprawnień użytkownika'
];

export const BEDevDescription = [
  'zaimplementowano nowe endpointy RESTful do obsługi zamówień',
  'dokonano optymalizacji zapytań SQL w celu poprawy wydajności bazy danych',
  'wdrożono mechanizmy cache\'owania odpowiedzi z API przy użyciu Redis',
  'przeprowadzono migrację aplikacji na najnowszą wersję Spring Boot',
  'naprawiono błędy związane z przetwarzaniem transakcji w systemie płatności',
  'zaimplementowano mechanizmy autoryzacji i uwierzytelniania użytkowników za pomocą JWT',
  'przeprowadzono testy integracyjne dla modułów komunikujących się z zewnętrznymi usługami',
  'skonfigurowano narzędzia do monitorowania i logowania zdarzeń w aplikacji',
  'przeanalizowano i wdrożono najlepsze praktyki dotyczące obsługi wyjątków',
  'omówiono wymagania i zdefiniowano zakres pracy dla modułu zarządzania użytkownikami',
  'przeprowadzono audyt bezpieczeństwa aplikacji pod kątem podatności na ataki',
  'zntegrowano aplikację z zewnętrzną usługą do wysyłania wiadomości e-mail',
  'przeprowadzono code review kodu odpowiedzialnego za obsługę płatności online',
  'wdrożono mechanizmy kolejkowania zadań przy użyciu RabbitMQ',
  'zaktualizowano dokumentację API w narzędziu Swagger',
  'przeprowadzono migrację danych z MySQL do PostgreSQL',
  'zaimplementowano mechanizmy ograniczania liczby żądań (rate limiting)',
  'zoptymalizowano algorytmy przetwarzania dużych zbiorów danych',
  'naprawiono problemy z kompatybilnością aplikacji na różnych środowiskach',
  'skonfigurowano środowisko testowe z wykorzystaniem Docker',
  'dodano obsługę wersjonowania API',
  'przeprowadzono testy wydajnościowe dla kluczowych endpointów',
  'wdrożono mechanizmy replikacji bazy danych dla zwiększenia dostępności',
  'skonfigurowano serwis do zarządzania sesjami użytkowników',
  'zaimplementowano system powiadomień w czasie rzeczywistym przy użyciu WebSocket'
];

export const TestsTeamDescription = [
  'przeprowadzono testy funkcjonalne nowych modułów aplikacji',
  'utworzono i zaktualizowano scenariusze testowe dla nowych funkcji',
  'zautomatyzowano testy regresyjne przy użyciu Selenium',
  'przeanalizowano wyniki testów wydajnościowych i zgłoszono znalezione problemy',
  'dokonano weryfikacji poprawek zgłoszonych błędów',
  'przeprowadzono testy integracyjne dla komponentów komunikujących się z API',
  'przygotowano raporty z testów i przekazano je do zespołu deweloperskiego',
  'wdrożono narzędzia do monitorowania jakości kodu',
  'skonfigurowano środowisko testowe przy użyciu Docker',
  'przeprowadzono testy użyteczności aplikacji z udziałem użytkowników końcowych',
  'opracowano testy jednostkowe dla krytycznych funkcji aplikacji',
  'zgłoszono błędy i śledzono ich status w systemie zarządzania błędami',
  'przeanalizowano logi serwera w celu identyfikacji potencjalnych problemów',
  'przeprowadzono testy kompatybilności aplikacji na różnych przeglądarkach',
  'wdrożono automatyzację testów API przy użyciu Postman',
  'przeprowadzono testy bezpieczeństwa aplikacji i zgłoszono luki',
  'przygotowano testowe dane wejściowe dla scenariuszy testowych',
  'weryfikowano zgodność aplikacji z wymaganiami biznesowymi',
  'przeprowadzono testy E2E dla kluczowych ścieżek użytkownika',
  'dokonano walidacji wydajności aplikacji pod kątem obciążenia',
  'przeprowadzono testy regresji po wdrożeniu nowych wersji oprogramowania',
  'współpracowano z zespołem deweloperskim w celu reprodukcji zgłoszonych błędów',
  'wdrożono narzędzia do ciągłej integracji i testowania',
  'dokonano oceny jakości kodu na podstawie wyników testów statycznych',
  'przygotowano scenariusze testowe dla testów akceptacyjnych'
];

export const AnalystsTeamDescription = [
  'przeanalizowano wymagania biznesowe i stworzenie dokumentacji technicznej',
  'zdefiniowano przypadki użycia dla nowej funkcjonalności systemu',
  'przeprowadzono analizę wymagań interesariuszy i przygotowano raport z wnioskami',
  'stworzono diagramy procesów biznesowych przy użyciu narzędzi BPMN',
  'zidentyfikowano luki w aktualnych procesach i zaproponowano rozwiązania',
  'przeprowadzono warsztaty zbierania wymagań z użytkownikami końcowymi',
  'opracowano mapę zależności pomiędzy modułami systemu',
  'sporządzono specyfikacje wymagań funkcjonalnych i niefunkcjonalnych',
  'przeprowadzono analizę ryzyka dla nowo wdrażanych funkcjonalności',
  'skonfigurowano narzędzia do śledzenia wymagań i ich statusu',
  'zebrano i przeanalizowano feedback od użytkowników końcowych',
  'przygotowano modele danych i diagramy ERD dla bazy danych',
  'wykonano analizę konkurencji i opracowano raport porównawczy',
  'opracowano scenariusze testowe dla walidacji wymagań biznesowych',
  'zidentyfikowano kluczowe wskaźniki wydajności (KPI) dla monitorowania postępów',
  'przeprowadzono analizę wpływu zmian na istniejące systemy',
  'uczestniczono w spotkaniach z zespołem deweloperskim w celu omówienia wymagań',
  'opracowano i przedyskutowano specyfikacje interfejsów API',
  'przygotowano plan migracji danych z istniejących systemów',
  'dokonano walidacji wymagań poprzez prototypowanie i testy użytkowników',
  'przeanalizowano dane z systemów analitycznych w celu identyfikacji trendów',
  'opracowano dokumenty przypadków użycia i scenariuszy użytkownika',
  'skonfigurowano narzędzia do analizy i wizualizacji danych',
  'przygotowano dokumentację techniczną dla nowych modułów systemu',
  'przeprowadzono analizę regresji w celu zidentyfikowania zależności między zmiennymi'
];
